### ISSUE TITLE
Maintain API token as part of state

### ISSUE THREAD

**Issue by dhrosa** [mpickering/slack-api#1]
I'm trying to write some code that interacts with the REST API, which needs to pass the API token into every request URL. Could the code be modified to keep the API token as part of the state, instead of losing it in runBot?

**Comment by mpickering** [comment]
Most of the methods in the REST API are unavailable to bot accounts. What exactly are you trying to do?

It does seem sensible to add it somewhere anyway.

**Comment by mpickering** [comment]
Does ca180bc solve your problem?

**Comment by dhrosa** [comment]
Yes it does, thanks!

From what I've seen, most of the API commands except for posting messages seem to work with a bot token.
