### ISSUE TITLE
Discuss: should slack-api be haddock'ed?

### ISSUE THREAD

**Issue by angerman** [mpickering/slack-api#11]
There are currently no haddock comments in the source.  Should this be added? Might make it easier to jump around. http://hackage.haskell.org/package/slack-api has no links at all. Is this a feature request or absent on purpose?

**Comment by mpickering** [comment]
It looks like the docs failed to build. Let me investigate.

**Comment by angerman** [comment]
Thanks, looking forward to it. The lens packages has it on github as well (http://ekmett.github.io/lens/frames.html). I don't know how much trouble it is to set that up though.

**Comment by mpickering** [comment]
I just manually uploaded the docs. Feel free to ask any questions if anything is unclear.
