### ISSUE TITLE
key "is_archived" not present

### ISSUE THREAD

**Issue by peddie** [mpickering/slack-api#19]
{"type":"channel_created","channel":{"id":"<elided>","is_channel":true,"name":"appliedmaths","created":1438929092,"creator":"<elided>"},"event_ts":"1438929092.870613"}
    key "is_archived" not present
    Please report this failure to the github issue tracker

Reporting as requested.  A follow-up channel list request using `curl` returns an `is_archived` field in the JSON map for this channel.  I guess Slack don't add the `is_archived` field before they announce that the channel has been created.

**Comment by mpickering** [comment]
Are you planning to make a pull request for this change as well?

**Comment by peddie** [comment]
Can do.  I'm not sure what the best approach to this one is.  What do you think -- make the `is_archived` field a `Maybe Bool`, or assume that `_channelIsArchived` is `False` if the field isn't present?

**Comment by mpickering** [comment]
That is what I have done in the past. With better API documentation I don't think there is much else to be done.
