### ISSUE TITLE
Unrecognised type: pin_removed (pin_added)

### ISSUE THREAD

**Issue by peddie** [mpickering/slack-api#24]
{"type":"pin_removed","user":"<elided>","channel_id":"<elided>","item":{"type":"message","channel":"<elided>","message":{"type":"message","user":"<elided>","text":"can we make Cheyne sing opera all the time?","ts":"1439001973.000817","permalink":"<elided>","reactions":[{"name":"+1","users":[<elided strings>],"count":6},{"name":"retrocoin","users":[<elided strings>],"count":5}]}},"has_pins":false,"event_ts":"1439241580.749454"}
    Unrecognised type: pin_removed
    Please report this failure to the github issue tracker

From the API docs for [this mystery event](https://api.slack.com/events/pin_removed):

> The pin_removed event is sent to all members of a channel when an item is pinned in that channel.
> 
> The format of this event type is still unstable and we expect to make changes to it in the future. Until the pinning APIs are released clients should ignore this event.

[The same goes for `pin_added`](https://api.slack.com/events/pin_added).

I can think of two approaches: either include these events anyway and try to keep the format up to date or ignore them in parsing so that they're not exposed to users but they don't cause error messages to get printed.

**Comment by mpickering** [comment]
Thank you once again. I think this is a case of adding a constructor to `Event`? Once again I apologise for this behaviour. Do you have any ideas how it could be better? Maybe erroring on unrecognised events isn't the best action?

**Comment by mpickering** [comment]
Oh, I see that it says it's unstable now.. I will just add a dummy constructor for now.

**Comment by peddie** [comment]
OK, I'm happy to deal with this if you don't want to -- just asking for guidance on the right change to make.

**Comment by peddie** [comment]
P.S. It seems like it would be better to not do a dummy constructor -- either do a real one that users can use or just ignore these event types in the `FromJSON` instance as the docs advise.

**Comment by mpickering** [comment]
I am making these changes now. I have added a constructor `PinAdded` with no arguments. I am also adding a constructor `UnknownEvent` which means that these changes won't break code in future.

**Comment by peddie** [comment]
Cool idea, thanks!  Note that `PinAdded` and `PinRemoved` are two different events.

I am more than happy to keep getting and reporting error messages when the Slack API does something unexpected.

**Comment by mpickering** [comment]
Thank you, that will be very useful as I no longer user slack regularly. Would you mind if I add you as a collaborator so that you can make any urgent changes if I'm not around?

**Comment by peddie** [comment]
I don't know the API very well, but if you're OK with me muddling along and deferring anything complicated to you, I'm happy to help.

My company has just switched to Slack, so I expect to get plenty of events that don't match up.

**Comment by mpickering** [comment]
I don't think anyone knows the API well, most fixes are mundane as you've probably experienced already.

How do these commits look - 01e0b39ea1386b7aa0e8e8545f283c380bc29cfe
- a6f3bfa5ee3db55d8de4880f76b219afbaf4fd1d

Maybe you could test them out for me when you get the change?

**Comment by peddie** [comment]
Those commits look OK to me.  I'll try to get them running in a few minutes.

**Comment by peddie** [comment]
01e0b39 is fine -- the `pin_added` message was handled OK.  I haven't come up with the right test case for a6f3bfa yet.  It seems pretty harmless if you want to land both.
