### ISSUE TITLE
key "is_general" not present

### ISSUE THREAD

**Issue by peddie** [mpickering/slack-api#27]
{"type":"channel_created","channel":{"id":"<elided>","is_channel":true,"name":"parents","created":1439250835,"creator":"<elided>"},"event_ts":"1439250835.968977"}
    key "is_general" not present
    Please report this failure to the github issue tracker

@mpickering, if it's alright with you, I'm going to keep opening issues for these even when the fix is straightforward, just to keep track of all these API mysteries explicitly.

**Comment by peddie** [comment]
The same thing happens with the `is_member` key.

**Comment by mpickering** [comment]
SGTM - maybe the `is_general` key got deprecated? IIRC there used to be a privileged room called `#general` which everyone joined by default - is that still the case. If it's unclear then best to keep it as a Bool and default it to False I think?

**Comment by peddie** [comment]
The `#general` room still exists and is mandatory.  I haven't seen any errors parsing `Channel` objects during normal operation -- they seem to only happen when a channel is created.

I'm happy to default to `False` if you like.

**Comment by peddie** [comment]
This was closed with #29.
