### ISSUE TITLE
Hackage version not up to date

### ISSUE THREAD

**Issue by geekingfrog** [mpickering/slack-api#35]
On hackage there is still the requirement `errors (>=1.4 && <2.0)`, which is clearly not what is in the cabal file in the repo. Any idea how to fix that ?
I'm pretty new to the haskell ecosystem so I'm not sure this is the right place to report the issue.

**Comment by mpickering** [comment]
You can use `--allow-newer` when installing and it should work. I should release a new version soon as there are a few small improvements.

**Comment by geekingfrog** [comment]
Thanks for the quick answer and for the work for this lib
