### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by markandrus** [mpickering/slack-api#36]
Hi, great library! It's been working for me fine locally, but now when I deploy I am seeing a parse error:

```
user error (Error in $.users[0].status: failed to parse field users: failed to parse field status: expected Text, encountered Null)
```

I may be able to dig in to the JSON messages if that would be helpful.

**Comment by mpickering** [comment]
Is that all of the error message? I can't find where it comes from immediately and it doesn't look very haskelly at first glance.

**Comment by markandrus** [comment]
Yes, that's the entire error message I observe before my application exits with 1. I assumed it must have something to do with https://github.com/mpickering/slack-api/blob/master/src/Web/Slack/Types/User.hs#L31? Is that an auto-generated Aeson error? My code is a very simple one-file adapter between slack and lambdabot: https://github.com/markandrus/slack-lambdabot-heroku/blob/master/src/Main.hs

**Comment by mpickering** [comment]
I think it's an autogenerated aeson error, I will try to make some time to have a closer look.

**Comment by mpickering** [comment]
A dump of the JSON which causes this would be very helpful.

**Comment by markandrus** [comment]
@mpickering the full JSON is some 27000 lines long, so if the `$.users[0].status` error message is to be trusted, maybe we could just look at the first user under the "users" key? Here it is (with sensitive information redacted):

```json
{
  "is_admin": false,
  "is_ultra_restricted": false,
  "is_bot": false,
  "tz": null,
  "has_files": false,
  "presence": "away",
  "name": "redacted",
  "tz_offset": -25200,
  "is_restricted": false,
  "is_owner": false,
  "deleted": false,
  "color": "c386df",
  "status": null,
  "real_name": "redacted",
  "profile": {
    "email": "redacted",
    "first_name": "redacted",
    "image_1024": "redacted",
    "real_name_normalized": "redacted",
    "image_512": "redacted",
    "title": "redacted",
    "image_32": "redacted",
    "real_name": "redacted",
    "image_192": "redacted",
    "image_72": "redacted",
    "image_48": "redacted",
    "image_original": "redacted",
    "last_name": "redacted",
    "image_24": "redacted"
  },
  "id": "U0AQJM0P5",
  "tz_label": "Pacific Daylight Time",
  "is_primary_owner": false
}
```

**Comment by mpickering** [comment]
I have asked upstream why it is `null`. The API is honestly a nightmare, thanks for reporting the bug.

**Comment by mpickering** [comment]
Upstream have confirmed that the `status` field has been deprecated. I am going to remove it from the API.

**Comment by mpickering** [comment]
Upload v0.6 to hackage which should fix this issue. Let me know if you have any more problems.

**Comment by markandrus** [comment]
Works for me with 0.6 now, thanks!
