### ISSUE TITLE
key "message" not present

### ISSUE THREAD

**Issue by mitchellwrosen** [mpickering/slack-api#37]
I have a bot that's just sitting idle in a channel and printing all `Event`s to stdout for me to look at. Saw this one time.

    {"type":"reaction_added","user":"U02JZ29PL","item":{"type":"message","channel":"C02JBL1SN","ts":"1445714383.000132"},"reaction":"skull","event_ts":"1445715911.712116"}
    key "message" not present
    Please report this failure to the github issue tracker

**Comment by mpickering** [comment]
I have reported it upstream.

**Comment by joehillen** [comment]
@mpickering I don't think this is an upstream issue.

This is happens we there is a emote reaction.

Here is another example:

```
{"type":"reaction_added","user":"...","item":{"type":"message","channel":"...","ts":"1452030494.000018"},"reaction":"heart","event_ts":"1452030526.291127","ts":"1452030526.000019"}
key "message" not present
Please report this failure to the github issue tracker
```

Either "message" needs to be treated as an optional field as in #32 or there needs to be a new `ReactionItem` that can handle this.

**Comment by mpickering** [comment]
So the docs have since been updated. https://api.slack.com/events/reaction_added

It seems that it is different to an `Item` but then doesn't specify what can actually be included.

**Comment by Gabriel439** [comment]
I ran into this issue, too:

```
key "message" not present
Please report this failure to the github issue tracker
```

**Comment by tfausak** [comment]
I also ran into this issue in the same situation as @mitchellwrosen and @joehillen. My echo bot was just sitting around and someone reacted to a message.

```
{"type":"reaction_added","user":"U0RGKR9NG","item":{"type":"message","channel":"D11L2687L","ts":"1461005789.000006"},"reaction":"+1","item_user":"U11KA7R62","event_ts":"1461006517.813615","ts":"1461006517.000007"}
Error in $.item: failed to parse field item: key "message" not present
Please report this failure to the github issue tracker
```

**Comment by mitchellwrosen** [comment]
I believe @mpickering is aware of the issue, but slack's docs don't actually include the schema of a `reaction_added`'s `item`, so he's not sure how to parse it.

**Comment by mpickering** [comment]
More people use this library than I thought so I will look to fix it shortly but I am quite busy. Mitchell is right that the docs don't provide a specification for the abbreviated object but I will at least add something so that there isn't a runtime error.

**Comment by mpickering** [comment]
Fixed.

**Comment by Gabriel439** [comment]
Thank you! :)
