### ISSUE TITLE
"image_default" key not present

### ISSUE THREAD

**Issue by dtchepak** [mpickering/slack-api#4]
When trying to connect using the Echobot example I get the following message:

    user error (key "image_default" not present)

I'm not sure if this is something I've done wrong, or a change in the API, or something specific to my Slack team.

**Comment by mpickering** [comment]
I imagine this is a change in the API. I will look into it tomorrow.

**Comment by mpickering** [comment]
I am able to connect to my test room. I had to reverse engineer most of the intricacies of the API so please let me know if anything else breaks. I'll change it to a `Maybe` for the meantime.

**Comment by mpickering** [comment]
I just released 0.3 which includes this change if you want to try again. I also added some tests to catch any future API changes and turned on travis. 

If you run into any more problems then please let me know.

**Comment by dtchepak** [comment]
Thanks @mpickering. I tried it out and ran into some other errors when trying out the EchoBot example. I hacked around them in [this commit](https://github.com/dtchepak/slack-api/commit/0e640864389da46e17e693716b559ab5cb65b0b1). Not sure why the API is returning different structures in my case.

As an aside, at one point I got a `user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))`. Any idea what causes this? (I'm not sure what I did to fix it either. :-\ Haskell newbie here).

**Comment by mpickering** [comment]
I think as the message suggests you need to try compiling with `-threaded`. I'm not sure exactly what you're trying to build.

Wrt the API errors, I left one comment where the docs didn't match what you had discovered. The other error is likely because I had to reverse engineer the entire bot specification, I will open another issue on their issue tracker.

**Comment by angerman** [comment]
I needed to make the same changes to the Bot.hs file as well. Also commented all the Int fields out in the TeamPreferneces and wrote slackhq that their format int's as strings.

**Comment by mpickering** [comment]
@angerman Thanks for the report. Where did you report the issue to them? I suspect that the "type" should actually be a string but has some (undocumented) correspondence.

**Comment by angerman** [comment]
Wrote them on twitter. https://twitter.com/angerman_io/status/563354381328715777

Should probably open a proper support request, but didn't get around doing it yet.

**Comment by mpickering** [comment]
Tweeting @slackapi usually gets a response.
