### ISSUE TITLE
Failed to parse a known event. reconnect_url.

### ISSUE THREAD

**Issue by tchakkazulu** [mpickering/slack-api#47]
I compiled the EchoBot from the example directory, and I got this message:

    Object (fromList [("url",String "wss://ms631.slack-msgs.com/websocket/blablabla"),("type",String "reconnect_url")])
    Failed to parse to a known event\n
    Please report this failure to the github issue tracker

(websocket URL obviously shortened)
This is slack-api-0.6 from hackage.

**Comment by madjar** [comment]
This should be fixed
