### ISSUE TITLE
haskell-slack-api-0.3 test suite failure

### ISSUE THREAD

**Issue by peti** [mpickering/slack-api#5]
Citing from http://hydra.cryp.to/build/536689/log/raw:

    running tests
    Running 1 test suites...
    Test suite tests: RUNNING...
    Test suite tests: FAIL

**Comment by mpickering** [comment]
An extra env variable needs to be set for the tests to succeed (as I don't want to expose my API token). What do you suggest?

**Comment by peti** [comment]
Well, we cannot hard-code such a token in our public build instructions either, so I guess we just cannot run the test suite in NixOS.
