### ISSUE TITLE
Link formatting 

### ISSUE THREAD

**Issue by tommyengstrom** [mpickering/slack-api#51]
Slack supports embedded links in the format: [\<URL|link name\>](https://api.slack.com/docs/formatting/builder?msg=%7B%22text%22%3A%22I%20am%20a%20test%20message%20%3Chttp%3A%2F%2Fwww.somedomain.com%7Clink%20name%3E%22%7D)

When appending such a link to the response of echoBot it is rendered as plain text.

**Comment by mpickering** [comment]
I asked upstream. The docs are unclear about what the expected behaviour is.

**Comment by mpickering** [comment]
> Sorry for the lack of documentation here — the RTM only supports plain text and limited formatting that you're familiar with using inside of the Slack client itself. Rich text links are not supported.

> For posting in formatted links we suggest using the chat.postMessage (https://api.slack.com/methods/chat.postMessage) instead, and if you're posting as a bot or user, please make sure to set as_user=true in the request so the message is attributed correctly.

We don't currently support the `postMessage` command and I don't play to add support for this to the library (as I don't use the library anymore).

**Comment by tommyengstrom** [comment]
Interesting design decision they have there.

Thank you very much for the help!
