### ISSUE TITLE
key "collapsible" was not present

### ISSUE THREAD

**Issue by Vlix** [mpickering/slack-api#52]
So this might be similar to the [key "message" was not present] issue from a while back, but my slackbot suddenly stopped working and gave the following error
"user error (When parsing the record Preferences of type Web.Slack.Types.Preferences.Preferences the key collapsible was not present.)"

This is through Yesod, so the error message may look different than a standalone slackbot, but it seems that the collapsible argument has been made optional on Slack's side?

**Comment by mpickering** [comment]
I will remove that field for now. If anyone ever wants it they are welcome to send a pull request to add it back in if they can get some assurance from slack HQ that it won't disappear.

**Comment by mpickering** [comment]
I released a new version with these changes.

**Comment by eikeon** [comment]
There seemed to be some new fields too? For example: seen_onboarding_start

**Comment by mpickering** [comment]
I don't know. If you want me to add support for these new fields then I can do but if no-one is going to use them then I would rather not bother as it is liable to break again.

**Comment by eikeon** [comment]
Thank you for the quick fix; back up and running with version 0.8 from Hackage.

@mpickering I don't need the new fields
