### ISSUE TITLE
new Exception parsing Preferences

### ISSUE THREAD

**Issue by eikeon** [mpickering/slack-api#53]
*** Exception: user error (When parsing the record Preferences of type Web.Slack.Types.Preferences.Preferences the key collapsible was not present.)

Did the Slack API change in the last day or two?

It looks like the prefs I'm getting from the API has many of the same keys but some missing as well as some new ones.

**Comment by eikeon** [comment]
I see someone else reported this after I checked. Closing this as a duplicate

**Comment by mpickering** [comment]
Thanks for the report. I removed the fields and released a new version. 

If you want to use any of the new fields then it is easy to add them.
