### ISSUE TITLE
Is there a way to create a ChannelId from String?

### ISSUE THREAD

**Issue by tonyd256** [mpickering/slack-api#54]
Is there a way to create any `Id` type with a `String` or other string-like type? I have a bunch of channel id strings stored in a database and I would like to use them to create `ChannelId` types so I can call `sendMessage` with them.

**Comment by mpickering** [comment]
Yes, sorry I didn't reply to this sooner. The way I intended for this to be done is

```
> review getId "abc"
Id "abc"
```

but this doesn't matter now that the constructors are exported.
