### ISSUE TITLE
Error when bot is kicked from a channel

### ISSUE THREAD

**Issue by matthewfranglen** [mpickering/slack-api#57]
I was testing this library using the echo bot. It all worked fine. When I kicked the bot from the channel this appeared in the logs:

```
{"type":"channel_left","channel":"C09EKGGEA"}
Error in $.channel: failed to parse field channel: expected Channel, encountered String
Please report this failure to the github issue tracker
MessagePayload {messageId = 3, messageType = "message", messageChannel = Id {_getId = "D135ZCWDC"}, messageText = "You have been removed from #general by <@U09EK8480|matthew>"}
```

**Comment by mpickering** [comment]
Thanks. Fixed in https://github.com/mpickering/slack-api/commit/4c8de20446d954d3c7ba335d0442b5bd49c65da3

You can try building master if you still run into the problem.
