### ISSUE TITLE
Groups and channels should perhaps not be separate

### ISSUE THREAD

**Issue by mwotton** [mpickering/slack-api#60]
Any private channel is actually a group, and there doesn't seem to be a way to send a message to a group.

If you use this 

```
dirtyConvert :: GroupId -> ChannelId
dirtyConvert (Id x) = Id x
```
and pretend it's a channel it works, but it's a bit awful.

**Comment by mwotton** [comment]
@mpickering thoughts? i'm happy to put together a PR for this, but want to know the basic direction you'd like to go before i waste my time on something unmergeable.

**Comment by mpickering** [comment]
I don't know. Are there situations where it is acceptable to supply a ChannelID but not a GroupID for example?

**Comment by mwotton** [comment]
as far as the docs go:

```
A group object contains information about a private channel. Private channels were once known as "private groups." Consider a group object the same thing as a private channel object.
```

https://api.slack.com/types/group

So the only reason to separate them would be if you were trying to enforce the public/private distinction, in which case you'd still need to implement the equivalent functions for Groups. If it's a valuable distinction, I'd suggest something like a phantom type parameter rather than a completely separate type.

**Comment by mpickering** [comment]
I'm find with removing the distinction.

**Comment by mwotton** [comment]
righto, PR incoming.
