### ISSUE TITLE
Drop OpenSSL?

### ISSUE THREAD

**Issue by angerman** [mpickering/slack-api#62]
I have locally replaced the OpenSSL dependency with tls + wuss.  If that would be of interest, I'd polish up a pull request.

**Comment by mpickering** [comment]
What do I use OpenSSl for?

**Comment by angerman** [comment]
OpenSSL is used for the SSL part of the websockets:

Usage here:
https://github.com/mpickering/slack-api/blob/master/src/Web/Slack.hs#L58

Dependency here:
https://github.com/mpickering/slack-api/blob/master/slack-api.cabal#L76

**Comment by mpickering** [comment]
If you think this is a good idea then sure. I think I just copy and pasted code.
