### ISSUE TITLE
Slacks stringly typed JSON

### ISSUE THREAD

**Issue by angerman** [mpickering/slack-api#63]
As noted in other tickets, the slack API seems to send malformed (or mixed typed?) JSON. I've another hack lying around that hooks into the `eitherDecode` function and does some type coercion on the JSON tree prior to actually parsing it.

Similarly to the other issue (#62) I just opened, I'd polish that a little and send a PR, if there's interest. This also allows to fix issues like #6, in the absence of administrator privileges (e.g. when the fix @tonyd256 provided, is not possible).

**Comment by mpickering** [comment]
How exactly does this work?

**Comment by angerman** [comment]
Given a a transformer (here `asNumber`) and the "path" to the potentially offending leaf in the JSON tree, I have the following correction function:
```haskell
    fixRetentionType = ((key "team" . key "prefs" . key "retention_type") `over` asNumber)
      . ((key "team" . key "prefs" . key "group_retention_type") `over` asNumber)
      . ((key "team" . key "prefs" . key "dm_retention_type") `over` asNumber)
```
and a slightly adapted `eitherDecode` that takes a function like `fixRetentionType` above, and applies it to the JSON object prior to feeding it into the decoder.

**Comment by mpickering** [comment]
This looks interesting. The approach I have been taking is just to remove the offending parts of the AST as they are usually not very widely used but this looks better when it is possible to properly debug what is going on.

I would accept a PR.
