### ISSUE TITLE
key `tab_ui_return_selects` missing

### ISSUE THREAD

**Issue by mitchellwrosen** [mpickering/slack-api#71]
Seeing this error:
```
user error (When parsing the record Preferences of type Web.Slack.Types.Preferences.Preferences the key tab_ui_return_selects was not present.)
```
I suppose API upstream has changed, then?

**Comment by mpickering** [comment]
Yes. If you send a pull request which deletes that field then I will upload a new version.

**Comment by mitchellwrosen** [comment]
Shouldn't it be a `Maybe` instead? Also - I tweeted @SlackAPI because I couldn't find any docs on the schema of the prefs field.

**Comment by mpickering** [comment]
If you like but I generally remove these fields as they are undocumented and not likely to be used by anyone. I suspect they completely removed the field anyway.

**Comment by mitchellwrosen** [comment]
:+1:

**Comment by mitchellwrosen** [comment]
Btw, @SlackAPI responded - https://twitter.com/SlackAPI/status/823610800392769536

They say the field is undocumented and probably best to ignore. Perhaps the prefs should just be left as an aeson `Value` until the API stabilizes?
