### ISSUE TITLE
key speak_growls was not present

### ISSUE THREAD

**Issue by michaelwillett** [mpickering/slack-api#74]
Not sure if this is a configuration issue on my end, but I just tried installing this today and can't seem to get past this issue.

`*** Exception: user error (When parsing the record Preferences of type Web.Slack.Types.Preferences.Preferences the key speak_growls was not present.)`

I am just trying to run the echoBot demo, but once I plug in my api-token, I get this issue as soon as it tries to parse a packet.

**Comment by mitchellwrosen** [comment]
As I mentioned in #71, Slack [said on Twitter](https://twitter.com/SlackAPI/status/823610800392769536), saying the preferences is undocumented and subject to change. I recommend just not trying to parse it into anything more specific than an aeson `Value`.

**Comment by jdreaver** [comment]
This particular issue was actually fixed in https://github.com/mpickering/slack-api/pull/73.

Agreed on just trying to parse into `Value`.

**Comment by mpickering** [comment]
I did a new release.
