### ISSUE TITLE
Echobot example: user error (expected Bool, encountered String)

### ISSUE THREAD

**Issue by srhb** [mpickering/slack-api#78]
It's not an auth error as I can get a different error if I put in a wrong token, but there's no helpful error message aside from this. Is there any way I can make it be more verbose?

**Comment by srhb** [comment]
The problem appears to originate in `makeSlackCall` (the `rtm.start` one) at

        rawResp <- liftIO $ W.getWith opts url

**Comment by srhb** [comment]
Hmm, no, I'm mistaken, it's the `sessionInfo` parse that's failing.

**Comment by srhb** [comment]
Yuck, debugging aeson errors is pain and horror. The issue is `teamIconDefault`

The JSON I'm receiving is `"image_default": "1",` which definitely isn't a `Maybe Bool`

**Comment by jship** [comment]
@srhb: I just hit this too.  PR submitted: #79

Hopefully slack will update docs/api for accuracy.  :slightly_smiling_face:

**Comment by mitchellwrosen** [comment]
Thanks @jship, merged.
